# 3. Hafta Lab-5: Karar Ağacı Algoritması
## BGM 565: Siber Güvenlik için Makine Öğrenme Yöntemleri
## İstanbul Şehir Üni. - Bilgi Güvenliği Müh.
### Dr. Ferhat Özgür Çatak
Bu lab çalışmasında karar ağacı yöntemini tenis veri kümesinde uygulayacağız.

In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score 
from sklearn.cross_validation import train_test_split

c:\users\user\appdata\local\programs\python\python35\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
# veri kumesini oku
df = pd.read_csv('tennis.txt') 
df

     outlook  temp humidity   windy play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [3]:
lb = LabelEncoder() 
df['outlook_'] = lb.fit_transform(df['outlook']) 
df['temp_'] = lb.fit_transform(df['temp'] ) 
df['humidity_'] = lb.fit_transform(df['humidity'] ) 
df['windy_'] = lb.fit_transform(df['windy'] )   
df['play_'] = lb.fit_transform(df['play'] ) 
X = df.iloc[:,5:9] 
y = df.iloc[:,9]

df

,outlook,temp,humidity,windy,play,outlook_,temp_,humidity_,windy_,play_
0,Sunny,Hot,High,Weak,No,2,1,0,1,0
1,Sunny,Hot,High,Strong,No,2,1,0,0,0
2,Overcast,Hot,High,Weak,Yes,0,1,0,1,1
3,Rain,Mild,High,Weak,Yes,1,2,0,1,1
4,Rain,Cool,Normal,Weak,Yes,1,0,1,1,1
5,Rain,Cool,Normal,Strong,No,1,0,1,0,0
6,Overcast,Cool,Normal,Strong,Yes,0,0,1,0,1
7,Sunny,Mild,High,Weak,No,2,2,0,1,0
8,Sunny,Cool,Normal,Weak,Yes,2,0,1,1,1
9,Rain,Mild,Normal,Weak,Yes,1,2,1,1,1
10,Sunny,Mild,Normal,Strong,Yes,2,2,1,0,1
11,Overcast,Mild,High,Strong,Yes,0,2,0,0,1
12,Overcast,Hot,Normal,Weak,Yes,0,1,1,1,1
13,Rain,Mild,High,Strong,No,1,2,0,0,0

In [4]:
X = df.iloc[:,5:9] 
y = df.iloc[:,9]
X

    outlook_  temp_  humidity_  windy_
0          2      1          0       1
1          2      1          0       0
2          0      1          0       1
3          1      2          0       1
4          1      0          1       1
5          1      0          1       0
6          0      0          1       0
7          2      2          0       1
8          2      0          1       1
9          1      2          1       1
10         2      2          1       0
11         0      2          0       0
12         0      1          1       1
13         1      2          0       0

In [5]:
clf_entropy = DecisionTreeClassifier(criterion='entropy')
clf_entropy.fit(X.astype(int),y) 
y_pred_en = clf_entropy.predict(X)

print("Accuracy is :{0}".format(accuracy_score(y.astype(int),y_pred_en) * 100))

Accuracy is :100.0